Prevent requirement of C99 mode
After aplying this patch nginx can't be build because:
```
src/event/ngx_event_openssl.c: In function 'ngx_SSL_client_features':
src/event/ngx_event_openssl.c:1628:17: error: 'for' loop initial declarations are only allowed in C99 mode
src/event/ngx_event_openssl.c:1628:17: note: use option -std=c99 or
-std=gnu99 to compile your code
```

This simple changes fixed it